name: Sync docs on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # every 3 hours

jobs:
  sync_scheduler:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3

    - name: Sync preview branch (multiple PRs) on schedule
      if: github.event_name == 'schedule' && github.event.schedule == '0 */3 * * *'
      run: |
        gh workflow run sync_mult_prs.yml --ref v8.4-preview
